name: packing release

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
          npm install
        env:
          CI: true
      - name: gulp generate zip
        run: |
          gulp rename
        env:
          CI: true
      - name: gulp release
        run: |
          gulp release
        env:
          CI: true

